sudo: required
services:
  - docker

branches:
  only:
    - master

before_install:
  - docker build -t techflookup/far-react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run techflookup/far-react-test npm test -- --coverage --watchAll=false

after_success:
  - docker build -t techflookup/far-client ./client
  - docker build -t techflookup/far-nginx ./nginx
  - docker build --build-arg jwt=$FAR_JWT_PRIVATEKEY mail_passwor=$FAR_MAIL_PASSWORD db_password=$FAR_DB_PASSWORD -t techflookup/far-auth  ./auth
  - docker build --build-arg jwt=$FAR_JWT_PRIVATEKEY mail_passwor=$FAR_MAIL_PASSWORD db_password=$FAR_DB_PASSWORD access_id=$AWS_ACCESS_KEY secret_key=$AWS_SECRET_KEY -t techflookup/far-api ./api

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push techflookup/far-client
  - docker push techflookup/far-nginx
  - docker push techflookup/far-auth
  - docker push techflookup/far-api

deploy:
  provider: elasticbeanstalk
  region: ap-south-1
  app: fixed-assets-beanstalk
  env: FixedAssetsBeanstalk-env
  bucket_name: elasticbeanstalk-ap-south-1-837962867465
  bucket_path: fixed-assets-beanstalk
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
